# Software profesional en Acústica 2024-25 (M2i)

*This notebook contains some code samples and text translated to Spanish from the notebooks [IA-maths-Jupyter](https://github.com/garth-wells/IA-maths-Jupyter), used in the course **Mathematical Models** in the University of Cambridge, and created by Garth N. Wells. All text is made available under the [Creative Commons Attribution-ShareAlike 4.0 International Public License](https://creativecommons.org/licenses/by-sa/4.0/legalcode). The code is released under the [MIT license](https://opensource.org/licenses/MIT).*

# Introducción

Trabajar con números es uno de los problemas comunes y centrales en cualquier faceta de la simulación numérica. Debido a su importancia, existe una gran cantidad de bibliotecas dedicadas a implementar métodos eficientes para manipular números y funciones. Incluso existen lenguajes y entornos de programación especialmente diseñados para este fin, como el lenguaje Fortran o Matlab/Octave.

Para el lenguaje Python, que será el que utilizaremos en la primera parte del curso *Software Profesional en Acústica*, la librería **NumPy** (http://www.numpy.org/) es la más utilizada para cálculos numéricos. Esta biblioteca utiliza una amplia gama de estructuras de datos y funciones para cálculos numéricos. En este cuaderno Jupyter, se revisarán algunas de estas características.

**NumPy** es una biblioteca enorme y tiene una funcionalidad muy amplia. Este guión de práctica solo representa una introducción muy breve. Para descubrir más funciones y cómo usarlo para muchos otros propósitos, la mejor fuente de información en línea son los motores de búsqueda, y en particular la comunidad http://stackoverflow.com/.

Para utilizar este script de práctica directamente desde una instalación de Python con *Anaconda*, simplemente haga clic en la aplicación 'Jupyter notebook' que ya está instalada de forma predeterminada (para más detalles: https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html).


## Objetivos

- Trabajar con objetos y métodos
- Introducción a matrices unidimensionales de números (`numpy.array`)
- Aplicar operaciones numéricas elementales
- Manipulación de vectores numéricos (indexación, corte, etc.)
- Ejercicio: eficiencia de **Numpy** en funciones vectorizadas y no vectorizadas

# Importar el módulo **NumPy**

Para tener **NumPy** disponible en su código, primero debe importar su módulo. Para ello se ha extendido mucho la costumbre de importar **Numpy** utilizando el atajo 'np':

In [1]:
import numpy as np

# Programación orientada a objetos

Como todos los módulos de Python, la biblioteca **Numpy** se implementa siguiendo una estrategia de programación orientada a objetos. Por lo tanto, cualquier estructura de datos en Python, incluso la más simple, debe entenderse como un objeto que pertenece a una clase, y todas las operaciones que podemos hacer con estos objetos son métodos implementados en esa clase de objetos. Incluso un número es un objeto de una clase:

In [2]:
a = 3.4
print(a)
print(type(a))
isinstance(a,float)

3.4
<class 'float'>


True

Para comprobar los atributos y métodos que podemos aplicar a un objeto concreto, podemos utilizar la función `dir()`, que devuelve una lista con sus nombres. Como puedes ver en la lista, podemos distinguir dos tipos de atributos y métodos: los que van con el prefijo y sufijo `__*__` y los que no. Los del primer tipo se denominan **privados** y suelen referirse a los cálculos más básicos que se pueden realizar dentro de la clase a la que pertenece el objeto.

In [3]:
dir(a)

['__abs__',
 '__add__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__set_format__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

Por ejemplo, podemos comprobar si un número real es mayor que otro de dos maneras diferentes: utilizando el operador lógico `>` o utilizando su método privado `__ge__`:

In [4]:
a=3.4; b=5.3
print(a.__gt__(b))
print(a > b)

False
False


En cualquier caso, en Python tanto los métodos privados como los públicos se utilizan de la misma manera. Por ejemplo:

In [ ]:
a=3.4
print(a.is_integer())
print(a.__int__())
print(int(a))

False
3
3


> **NOTA**: En este curso no trabajaremos ni será necesario implementar código utilizando programación orientada a objetos. Pero lo que será necesario es estar atentos a cuándo se utilizan objetos de diferentes clases y qué atributos y métodos se definen en cada caso.

# Vectores de números

En Python hay muchas formas de almacenar datos numéricos (o no), como la estructura de lista o tupla. En particular, las listas pueden contener una secuencia finita de números ordenados (y utilizar un índice para acceder a cada uno de los elementos de la lista). Además, son lo suficientemente flexibles para contener datos de diferente naturaleza (combinaciones de números enteros, números reales, listas de listas, etc.).

Pero esta flexibilidad de las listas en Python hace que su rendimiento computacional sea muy limitado. En la mayoría de las aplicaciones científicas en matemáticas e ingeniería de datos, los problemas del mundo real involucran operaciones en enormes conjuntos de datos y, por lo tanto, la velocidad computacional es muy importante para estos grandes problemas. Para trabajar eficientemente con estos problemas, **Numpy** proporciona funciones especializadas y estructuras de datos para un cálculo numérico eficiente. En particular, para el caso de arreglos de números del mismo tipo (perdiendo algo de la flexibilidad de las listas pero ganando eficiencia computacional).

## Vectores unidimensionales

Un vector unidimensional es una colección ordenada de números a la que se puede acceder mediante un índice (que preserva el orden). De forma predeterminada, los vectores en **Numpy** son vectores de fila.

### Creación e indexación de vectores

Para crear un vector **Numpy** de longitud 10 e inicializado con ceros, se utilizaría la función `np.zeros()`:

In [6]:
u = np.zeros(10)
print(u)
print(type(u))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


El tipo predeterminado de números contenidos en vectores en **Numpy** es `float64` (que es el tipo almacenado en `np.float`). Si desea utilizar otros tipos, debe utilizar el argumento opcional "dtype". El tipo de números contenidos en un vector se puede comprobar accediendo al atributo `dtype` de los vectores **Numpy**:

In [ ]:
print(u.dtype)
w = np.zeros(5, dtype=int)
print(w)
print(type(w))
print(w.dtype)

float64
[0 0 0 0 0]
<class 'numpy.ndarray'>
int64


Lo que no es posible, por ejemplo, es agregar un valor de cadena de texto (de tipo `string`) a un objeto `numpy.ndarray`, ya que todos los elementos del vector deben ser del mismo tipo (o de un tipo que admita una conversión) y también deben tener el mismo tamaño. Para comprobar el tamaño de un vector, se puede utilizar la función `len`:

In [ ]:
print(len(u))
v = np.zeros(10, dtype=int)
print(u + v) # Implicitamente se hace una conversión de tipo de int64 a float64
print(u + w) # ERROR: los vectores no tienen el mismo tamaño!

10
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: operands could not be broadcast together with shapes (10,) (5,) 

Una forma más específica de comprobar la dimensión de un vector es utilizar `u.shape`, que devuelve una tupla con las dimensiones del vector:

In [10]:
print(u.shape)

(10,)


`shape` nos informa sobre el tamaño del vector en *cada* dirección. En el caso de los vectores, solo hay una única dirección, mientras que en conjuntos de datos con múltiples índices (matrices o tensores de $n$ dimensiones) `shape` nos informaría del tamaño de estas estructuras de datos en cada dirección. Por ejemplo, para crear una matriz de enteros de ceros de tamaño $2\times 3$:

In [ ]:
A =  np.zeros((2,3), dtype=int)
print(A)
print(A.shape)

[[0 0 0]
 [0 0 0]]
(2, 3)


Podemos también cambiar las entradas de un vector usando sus índices,

In [12]:
print(u)
u[0] = 10.0
u[3] = -4.3
u[9] = 1.0
print(u)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[10.   0.   0.  -4.3  0.   0.   0.   0.   0.   1. ]


> **NOTA IMPORTANTE**: ¡Recuerde que los valores del índice comienzan en cero!

Obviamente, hay otras formas de crear vectores, como usar la función `ones` para crear un vector que contenga solo `ones`:

In [13]:
w = np.ones(5)
print(w)
print(w.dtype)

[1. 1. 1. 1. 1.]
float64


o un vector de valores aleatorios:

In [14]:
w = np.random.rand(6)
print(w)

[0.99555636 0.21770343 0.82258275 0.79557819 0.26750689 0.2909781 ]


o también un vector de números de tipo `numpy.array` a partir de una lista Python de números:

In [15]:
u = [4.0, 8.0, 9.0, 11.0, -2.0]
v = np.array(u)
print(v)

[ 4.  8.  9. 11. -2.]


Existen otros dos métodos para crear vectores de números que nos serán útiles a lo largo del curso (y en particular cuando tengamos que graficar funciones en una o varias variables):
- `numpy.arange`
- `numpy.linspace`

La función `arange` crea un vector con valores enteros consecutivos (similar a la función `range` de Python). Para crear el vector de fila $\vec{u}=(0, 1, 2, 3, 4, 5)$ usando `arange`:

In [16]:
u = np.arange(6)
print(u)
print(type(u))
print(u.dtype)

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int64


Podemos verificar que el número $6$ no está incluido ya que el rango de valores comienza en $0$ y el vector solo tiene seis elementos. Para cambiar el valor numérico en el que comienza el vector:

In [17]:
u = np.arange(2, 6)
print(u)

[2 3 4 5]


La función `linspace` crea un vector de números igualmente espaciados con un valor inicial y final (ambos incluidos) y un tamaño determinado:

In [18]:
w = np.linspace(0., 100., 6)
print(w)
print(w.dtype)

[  0.  20.  40.  60.  80. 100.]
float64


Esta función `linspace` junto con la función `meshgrid` se utilizarán ampliamente para trazar funciones de una y varias variables a lo largo de este curso.

### Funciones y aritmética sobre vectores

Los vectores en **NumPy** admiten operaciones aritméticas básicas como producto, suma y resta:

In [19]:
a = np.array([1.0, 0.2, 1.2])
b = np.array([2.0, 0.1, 2.1])
print(a)
print(b)

# Suma de a e b
c = a + b
print(c)

[1.  0.2 1.2]
[2.  0.1 2.1]
[3.  0.3 3.3]


y en el caso del producto de sus elementos por un valor escalar,

In [20]:
c = 10.0*a
print(c)

[10.  2. 12.]


y elevar sus componentes a una potencia:

In [21]:
a = np.array([2, 3, 4])
print(a**2)

[ 4  9 16]


También se pueden aplicar las funciones de cálculo usual a cada una de sus componentes:

In [ ]:
# Crear un vector [0, π/2, π, 3π/2]
a = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
print(a)

# Calcular el seno de cada componente del vector
b = np.sin(a)
print(b)

[0.         1.57079633 3.14159265 4.71238898]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


El código anterior calcula el seno de cada coeficiente del vector `a`. Debemos tener en cuenta que la función que se utiliza es `np.sin`, que depende directamente del módulo **Numpy**. El uso de cualquier otra implementación de la función en otros módulos (por ejemplo en el módulo **Math**) podría generar un error.

Obviamente, también podríamos calcular el seno de cada coeficiente del vector, accediendo a cada uno de los elementos por su índice y haciendo los cálculos dentro de un bucle `for`:

In [23]:
b = np.zeros(len(a))
for i in range(len(a)):
    b[i] = np.sin(a[i])

print(b)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


En este caso el programa es más largo y más difícil de leer. Además, en muchos casos será más lento. La manipulación de vectores y cualquier cálculo realizado entre ellos sin acceder a los índices se denominará "vectorización". Cuando sea posible, el uso de la vectorización aumentará el rendimiento y la velocidad de los códigos de cálculo. En el ejercicio final de este guión se analizará el desempeño de este tipo de técnicas.

# Troceado de vectores

Cuando se trabaja con vectores de números, es común tener que extraer un subconjunto de ellos para crear un nuevo vector. Por ejemplo, obtener los tres primeros coeficientes de un vector o en el caso de matrices, restringir los cálculos a su segunda columna. Este tipo de operación se llama segmentación de matrices.

Exploremos esto a través de varios ejemplos, comenzando trabajando con un vector de valores aleatorios:

In [24]:
a = np.random.rand(5)
print(a)

[0.88845599 0.87455961 0.75346135 0.49637203 0.53932423]


En lo que sigue, se realizarán varias operacións de troceado:

In [ ]:
# Usar ':' implica el conjunto entero en el rango de los índices, es decir, desde 0 hasta (longitud-1)
b = a[:]
print("Troceado usando '[:]' {}".format(b))

# Usar '1:3' implica los índices 1 -> 3 (sin incluir a 3)
b = a[1:3]
print("Troceado usando '[1:3]': {}".format(b))

# Usar '2:-1' implica los índices 2 -> el segundo desde el final (sin incluirlo)
b = a[2:-1]
print("Troceado usando '[2:-1]': {}".format(b))

# Usar '2:-2' implica los índices 2 -> el tercero desde el final (sin incluirlo)
b = a[2:-2]
print("Troceado usando '[2:-2]': {}".format(b))

Troceado usando '[:]' [0.88845599 0.87455961 0.75346135 0.49637203 0.53932423]
Troceado usando '[1:3]': [0.87455961 0.75346135]
Troceado usando '[2:-1]': [0.75346135 0.49637203]
Troceado usando '[2:-2]': [0.75346135]


> **NOTA**: el uso del índice `-1` corresponde al último elemento del vector. De manera similar, el índice `-2` está vinculado al segundo elemento comenzando desde el final, etc. Esta convención de referenciar índices desde el final de un vector es muy útil ya que con el uso de estos índices negativos, uno puede hacer referencia a los últimos coeficientes de un vector sin tener que referirse explícitamente al tamaño del vector.

Si desea cortar un vector desde el principio o el final, debe utilizar la sintaxis de índice con '`:`'

In [ ]:
# Usar ':3' implica usar índices desde el comienzo hasta 3 (sin incluir el índice 3)
b = a[:3]
print("Troceado usando '[:3]': {}".format(b))

# Usar '4:' imlica os índices desde 4 -> hasta el final
b = a[4:]
print("Troceado usando '[4:]': {}".format(b))

# Usar ':' implica todos os índices desde el comienzo hasta el final
b = a[:]
print("Troceado usando '[:]': {}".format(b))

Troceado usando '[:3]': [0.88845599 0.87455961 0.75346135]
Troceado usando '[4:]': [0.53932423]
Troceado usando '[:]': [0.88845599 0.87455961 0.75346135 0.49637203 0.53932423]


El troceado también se puede aplicar sobre matrices:

In [ ]:
B = np.array([[1.3, 0], [0, 2.0]])
print(B)

# Extraer la segunda fila
row = B[1, :]
print(row)

# Extraer la primera columna (almacenada en un vector fila)
col = B[:, 0] 
print(col)

[[1.3 0. ]
 [0.  2. ]]
[0. 2.]
[1.3 0. ]


Hay muchas otras estrategias y sintaxis relacionadas con el corte vectorial, que están más allá del alcance de esta breve introducción a **Numpy**. Para obtener información más detallada, puede consultar: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

# Ejercicio: Acelerando con Numpy el cálculo de normas vectoriales

La norma euclidiana (o módulo) de un vector $\vec{x}=(x_{0},\ldots,x_{n-1})\in\mathbb{R}^{n}$ está dada por

$$
\| x \| = \sqrt{\sum_{i=0}^{n-1} x_{i} x_{i}}
$$

donde $x_{i}$ es el $i$-ésimo coeficiente de $\vec{x}$. En resumen, su norma no es más que el cálculo del producto interno por sí mismo, seguido del cálculo de una raíz cuadrada. Para calcular el valor de la norma se pueden seguir diferentes estrategias: la primera de ellas puede ser utilizar un bucle para iterar sobre todos los coeficientes del vector y sumar el cuadrado de cada coeficiente. Luego toma la suma de todas estas cantidades y calcula la raíz cuadrada.

Para evaluar el rendimiento computacional de esta implementación, tomaremos un vector de longitud 10 millones y calcularemos el tiempo de cálculo:

In [ ]:
# Crear un vector NumPy con 10 millones de valores aleatorios
x = np.random.rand(10000000)
print(type(x))

<class 'numpy.ndarray'>


In [29]:
def compute_norm(x):
    norm = 0.0
    for xi in x:
        norm += xi*xi
    return np.sqrt(norm)

%time norm = compute_norm(x)
print(norm)

CPU times: user 3.19 s, sys: 15.6 ms, total: 3.2 s
Wall time: 3.2 s
1825.7437030008014


El tiempo de cálculo que nos interesa es el que aparece bajo la etiqueta 'Wall time'.

> **NOTA**: Los detalles de cómo funciona la etiqueta `%time` en este script no son importantes en este curso. Debemos indicar que esta forma de proceder sólo es válida para consolas o archivos que corran bajo entornos de servidores [I]Python y Jupyter. Esta forma de trabajar es muy compacta y conveniente para medir el tiempo necesario para completar la ejecución de una línea de código.

### **Ejercicio**
Utilizando la misma implementación basada en bucles, acceda a cada elemento del vector por su índice comenzando desde el primero hasta el último. Haga lo mismo con un bucle que acceda en orden inverso, del último al primero.

In [ ]:
# TU CÓDIGO AQUÍ


### **Ejercicio**
Intente utilizar funciones **Numpy** para definir una función que evite recorrer los coeficientes del vector y no acceda elemento por elemento en el vector (versión vectorizada).

In [ ]:
# TU CÓDIGO AQUÍ


### **Ejercicio**
Compare los tiempos de cálculo de las cuatro implementaciones para diferentes dimensiones del vector $\vec{x}$, de tamaños $10$, $10^3$, $10^5$, $10^7$. De estos tiempos de cálculo: ¿qué se puede deducir como conclusión?

In [ ]:
# TU CÓDIGO AQUÍ
